# Generated by Django 4.1.6 on 2023-03-19 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_budget', models.IntegerField()),
                ('donation_temperature', models.IntegerField(default=0)),
                ('total_donation', models.IntegerField(default=0)),
                ('donation_count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'User_Custom',
                'managed': True,
            },
        ),
    ]
