# Generated by Django 4.1.6 on 2023-03-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_custom',
            name='authority',
            field=models.BooleanField(default=False),
        ),
    ]
