# Generated by Django 4.1.6 on 2023-03-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0003_alter_user_custom_donation_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_custom',
            options={'managed': False},
        ),
    ]
