# Generated by Django 4.1.6 on 2023-03-04 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_custom', '0004_alter_user_custom_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user_custom',
            table='User_Custom',
        ),
    ]
