# Generated by Django 4.1.6 on 2023-03-19 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation_Point',
            fields=[
                ('donation_point_id', models.AutoField(primary_key=True, serialize=False)),
                ('point', models.IntegerField()),
                ('expiry_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'Donation_Point',
                'managed': True,
            },
        ),
    ]
