# Generated by Django 4.1.6 on 2023-03-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation_point', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation_point',
            options={'managed': False},
        ),
    ]
