# Generated by Django 4.1.6 on 2023-03-04 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation_point', '0002_alter_donation_point_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='donation_point',
            table='Donation_Point',
        ),
    ]
