# Generated by Django 4.1.6 on 2023-03-29 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation_point', '0002_remove_donation_point_expiry_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donation_Point',
        ),
    ]
