# Generated by Django 4.1.6 on 2023-05-17 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('donation_point', '0003_delete_donation_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation_Point',
            fields=[
                ('donatitonpoint_id', models.AutoField(primary_key=True, serialize=False)),
                ('paymentkey', models.CharField(max_length=200)),
                ('approvedAt', models.DateTimeField()),
                ('method', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('orderId', models.CharField(max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'Donation_Point',
                'managed': True,
            },
        ),
    ]
