# Generated by Django 4.1.6 on 2023-05-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_point', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation_point',
            name='approvedAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
