# Generated by Django 4.1.6 on 2023-03-03 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'managed': False},
        ),
    ]
