# Generated by Django 4.1.6 on 2023-03-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_campaign',
            name='donation_amount',
            field=models.IntegerField(default=0),
        ),
    ]
