# Generated by Django 4.1.6 on 2023-03-03 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_alter_campaign_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='campaign',
            table='Campaign',
        ),
    ]
