# Generated by Django 4.1.6 on 2023-03-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_alter_campaign_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user_campaign',
            options={'managed': False},
        ),
    ]
