# Generated by Django 4.1.6 on 2023-03-04 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_alter_message_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='message',
            table='Message',
        ),
        migrations.AlterModelTable(
            name='review',
            table='Review',
        ),
        migrations.AlterModelTable(
            name='user_campaign',
            table='User_Campaign',
        ),
    ]
