# Generated by Django 4.1.6 on 2023-05-24 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_notificaiton'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notificaiton',
            new_name='Notification',
        ),
    ]
