# Generated by Django 4.1.6 on 2023-05-24 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_rename_notificaiton_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='camapaign',
            new_name='campaign',
        ),
    ]
