# Generated by Django 4.1.6 on 2023-03-19 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Record',
            fields=[
                ('userrecord_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_budget', models.IntegerField()),
                ('today_date', models.DateTimeField()),
                ('comsumption', models.IntegerField()),
                ('donation', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'User_Record',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('when', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('memo', models.TextField()),
                ('settlement', models.BooleanField()),
                ('userrecord', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_record.user_record')),
            ],
            options={
                'db_table': 'Record',
                'managed': True,
            },
        ),
    ]
