# Generated by Django 4.1.6 on 2023-02-19 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_budget', models.IntegerField()),
                ('today_date', models.DateTimeField()),
                ('comsumption', models.IntegerField()),
                ('donation', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('memo', models.TextField()),
                ('settlement', models.BooleanField()),
                ('user_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_record.user_record')),
            ],
        ),
    ]
