# Generated by Django 4.1.6 on 2023-03-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_record', '0002_alter_user_record_today_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='memo',
            field=models.TextField(null=True),
        ),
    ]
