# Generated by Django 4.1.6 on 2023-03-04 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_record', '0002_alter_record_options_alter_user_record_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='record',
            table='Record',
        ),
        migrations.AlterModelTable(
            name='user_record',
            table='User_Record',
        ),
    ]
