# Generated by Django 4.1.6 on 2023-03-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_record', '0003_alter_record_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_record',
            name='differ',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='record',
            name='settlement',
            field=models.BooleanField(default=False),
        ),
    ]
